#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo "-- [pre-commit] Preparing commit..."
RET=0

# remove useless branches
echo "-- [pre-commit] Removing useless branch..."
git remote prune origin

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi
# 
# # If you want to allow non-ASCII filenames set this variable to true.
# allownonascii=$(git config --bool hooks.allownonascii)
# 
# # Redirect output to stderr.
# exec 1>&2
# 
# # Cross platform projects tend to avoid non-ASCII filenames; prevent
# # them from being added to the repository. We exploit the fact that the
# # printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	RET=1
fi

# format code
# CHANGED_CODE=$(git diff --cached --name-only)
# if [ -z "$CHANGED_CODE" ]; then
#   exit $RET
# fi
# CLANG_FORMAT=`which clang-format`
# if [ "$CLANG_FORMAT" != "" ]; then
#   echo "-- [pre-commit] Using clang-format to format code..."
#   for item in $CHANGED_CODE; do
#     echo "-- [pre-commit] Formatting $item..."
#     $CLANG_FORMAT -i -style=.clang-foramt $item
#     # git add $item
#   done
# else
#   echo "-- [pre-commit] Didn't find clang-format, skip formating code..."
# fi

exit $RET
